name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: theos/setup-theos@v1  # Esta versión es la correcta

      - name: Build Package
        run: make package FINALPACKAGE=1
